//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteBanco.BancoServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/BancoService")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_OperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Operacion {
            get {
                return this.Fecha_OperacionField;
            }
            set {
                if ((this.Fecha_OperacionField.Equals(value) != true)) {
                    this.Fecha_OperacionField = value;
                    this.RaisePropertyChanged("Fecha_Operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Operacion {
            get {
                return this.OperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionField, value) != true)) {
                    this.OperacionField = value;
                    this.RaisePropertyChanged("Operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BancoServicio.IBancoServicio")]
    public interface IBancoServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServicio/Depositar", ReplyAction="http://tempuri.org/IBancoServicio/DepositarResponse")]
        void Depositar(int cantidad, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServicio/Depositar", ReplyAction="http://tempuri.org/IBancoServicio/DepositarResponse")]
        System.Threading.Tasks.Task DepositarAsync(int cantidad, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServicio/Retirar", ReplyAction="http://tempuri.org/IBancoServicio/RetirarResponse")]
        void Retirar(int Cantidad, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServicio/Retirar", ReplyAction="http://tempuri.org/IBancoServicio/RetirarResponse")]
        System.Threading.Tasks.Task RetirarAsync(int Cantidad, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServicio/Extracto", ReplyAction="http://tempuri.org/IBancoServicio/ExtractoResponse")]
        ClienteBanco.BancoServicio.Cliente[] Extracto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServicio/Extracto", ReplyAction="http://tempuri.org/IBancoServicio/ExtractoResponse")]
        System.Threading.Tasks.Task<ClienteBanco.BancoServicio.Cliente[]> ExtractoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBancoServicioChannel : ClienteBanco.BancoServicio.IBancoServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BancoServicioClient : System.ServiceModel.ClientBase<ClienteBanco.BancoServicio.IBancoServicio>, ClienteBanco.BancoServicio.IBancoServicio {
        
        public BancoServicioClient() {
        }
        
        public BancoServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BancoServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Depositar(int cantidad, int id) {
            base.Channel.Depositar(cantidad, id);
        }
        
        public System.Threading.Tasks.Task DepositarAsync(int cantidad, int id) {
            return base.Channel.DepositarAsync(cantidad, id);
        }
        
        public void Retirar(int Cantidad, int id) {
            base.Channel.Retirar(Cantidad, id);
        }
        
        public System.Threading.Tasks.Task RetirarAsync(int Cantidad, int id) {
            return base.Channel.RetirarAsync(Cantidad, id);
        }
        
        public ClienteBanco.BancoServicio.Cliente[] Extracto(int id) {
            return base.Channel.Extracto(id);
        }
        
        public System.Threading.Tasks.Task<ClienteBanco.BancoServicio.Cliente[]> ExtractoAsync(int id) {
            return base.Channel.ExtractoAsync(id);
        }
    }
}
